services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db-dis

  db:
    image: postgres:15
    container_name: 'db-dis'
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

networks:
  default:
    driver: bridge
